"use client";

import { useState } from "react";
import { useAccount, useBalance, useConnect, useDisconnect } from "wagmi";

export default function TradePage() {
  const { address, isConnected } = useAccount();
  const { data: opnBalance } = useBalance({
          address,
          });
    const { connect, connectors } = useConnect();
      const { disconnect } = useDisconnect();

        const [amountIn, setAmountIn] = useState("");

          return (
              <main className="min-h-screen flex items-center justify-center p-4 bg-gradient-to-br from-indigo-600 via-pink-500 to-orange-400">

                    {/* Card */}
                          <div className="w-full max-w-md rounded-3xl bg-white/10 backdrop-blur-xl border border-white/20 shadow-2xl p-5 text-white">

                                  {/* Header */}
                                          <div className="text-center mb-6">
                                                    <h1 className="text-3xl font-bold">IOPN Swap</h1>
                                                              <p className="text-white/70 text-sm">
                                                                          Wallet connected via Wagmi (no RainbowKit)
                                                                                    </p>
                                                                                            </div>

                                                                                                    {/* Wallet Button (OPTION A CORE FIX) */}
                                                                                                            <div className="flex justify-center mb-6">
                                                                                                                      <button
                                                                                                                                  onClick={() =>
                                                                                                                                                isConnected
                                                                                                                                                                ? disconnect()
                                                                                                                                                                                : connect({ connector: connectors[0] })
                                                                                                                                                                                            }
                                                                                                                                                                                                        className="px-6 py-3 rounded-2xl font-bold bg-white text-black hover:scale-105 transition"
                                                                                                                                                                                                                  >
                                                                                                                                                                                                                              {isConnected ? "Disconnect Wallet" : "Connect Wallet"}
                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                {isConnected && (
                                                                                                                                                                                                                                                          <div className="mb-6 text-center">
                                                                                                                                                                                                                                                              <p className="text-xs break-all">
                                                                                                                                                                                                                                                                    {address}
                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                            <p className="font-bold mt-2">
                                                                                                                                                                                                                                                                                  Balance: {opnBalance?.formatted} {opnBalance?.symbol}
                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                        {/* Pay */}
                                                                                                                                                                                                                                                                <div className="rounded-2xl bg-white/10 p-4 mb-4 border border-white/10">
                                                                                                                                                                                                                                                                          <p className="text-sm text-white/70 mb-2">You Pay</p>

                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                type="number"
                                                                                                                                                                                                                                                                                                            placeholder="0.0"
                                                                                                                                                                                                                                                                                                                        value={amountIn}
                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setAmountIn(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                className="w-full bg-transparent outline-none text-3xl font-bold"
                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                          {/* Arrow */}
                                                                                                                                                                                                                                                                                                                                                                                  <div className="text-center text-white/60 text-2xl mb-4">
                                                                                                                                                                                                                                                                                                                                                                                            ↓
                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                            {/* Receive */}
                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="rounded-2xl bg-white/10 p-4 mb-6 border border-white/10">
                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-sm text-white/70 mb-2">You Receive</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-3xl font-bold text-white/80">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    Swap Coming Soon
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Button */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full rounded-2xl py-4 font-bold text-lg
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bg-gradient-to-r from-yellow-300 via-pink-400 to-purple-500
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text-black opacity-60 cursor-not-allowed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Swap Coming Soon
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }