export default function ExplorerPage() {
      return (
          <div className="p-6">
                <h1 className="text-3xl font-bold mb-6">
                        IOPn Explorer
                              </h1>

                                    <div className="grid gap-4">
                                            <div className="border rounded-xl p-5">
                                                      <h2 className="text-xl font-bold mb-2">
                                                                  Network Information
                                                                            </h2>

                                                                                      <p>
                                                                                                  <strong>Network:</strong> IOPn Testnet
                                                                                                            </p>

                                                                                                                      <p>
                                                                                                                                  <strong>Chain ID:</strong> 984
                                                                                                                                            </p>
                                                                                                                                                    </div>

                                                                                                                                                            <div className="border rounded-xl p-5">
                                                                                                                                                                      <h2 className="text-xl font-bold mb-2">
                                                                                                                                                                                  RPC Endpoint
                                                                                                                                                                                            </h2>

                                                                                                                                                                                                      <a
                                                                                                                                                                                                                  href="https://testnet-rpc.iopn.tech"
                                                                                                                                                                                                                              target="_blank"
                                                                                                                                                                                                                                          rel="noopener noreferrer"
                                                                                                                                                                                                                                                      className="text-blue-500 hover:underline"
                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                            https://testnet-rpc.iopn.tech
                                                                                                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                      <div className="border rounded-xl p-5">
                                                                                                                                                                                                                                                                                                                <h2 className="text-xl font-bold mb-2">
                                                                                                                                                                                                                                                                                                                            Quick Links
                                                                                                                                                                                                                                                                                                                                      </h2>

                                                                                                                                                                                                                                                                                                                                                <div className="flex flex-col gap-2">
                                                                                                                                                                                                                                                                                                                                                            <a
                                                                                                                                                                                                                                                                                                                                                                          href="/tokens"
                                                                                                                                                                                                                                                                                                                                                                                        className="text-blue-500 hover:underline"
                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                  View Tokens
                                                                                                                                                                                                                                                                                                                                                                                                                              </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                          <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                        href="/pairs"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="text-blue-500 hover:underline"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                View Trading Pairs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      href="/analytics"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="text-blue-500 hover:underline"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              View Analytics
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    href="/markets"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="text-blue-500 hover:underline"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            View Markets
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="border rounded-xl p-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="text-xl font-bold mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        About
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        IOPn Dex Analytics provides token analytics,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    trading pair analytics, portfolio tracking,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                market statistics, and explorer tools for the
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            IOPn ecosystem.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }