"use client";

type BalanceCardProps = {
  balance: string;
    token: string;
      address?: string;
        onReceive: () => void;
          onScanner: () => void;
            onVirtualCard: () => void;
            };

            export default function BalanceCard({
              balance,
                token,
                  address,
                    onReceive,
                      onScanner,
                        onVirtualCard,
                        }: BalanceCardProps) {
                          const shortAddress = address
                              ? `${address.slice(0, 6)}...${address.slice(-4)}`
                                  : "Wallet not connected";

                                    return (
                                        <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-emerald-500 via-green-500 to-teal-600 p-6 shadow-2xl">

                                              {/* Background Glow */}
                                                    <div className="absolute -right-16 -top-16 h-48 w-48 rounded-full bg-white/10 blur-3xl" />
                                                          <div className="absolute -left-10 bottom-0 h-32 w-32 rounded-full bg-black/10 blur-2xl" />

                                                                <div className="relative z-10">

                                                                        {/* Header */}
                                                                                <div className="flex items-center justify-between">
                                                                                          <div>
                                                                                                      <p className="text-sm text-white/80">
                                                                                                                    Available Balance
                                                                                                                                </p>

                                                                                                                                            <h1 className="mt-2 text-4xl font-bold text-white">
                                                                                                                                                          {balance} {token}
                                                                                                                                                                      </h1>

                                                                                                                                                                                  <p className="mt-2 text-xs text-white/80 break-all">
                                                                                                                                                                                                {shortAddress}
                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                <div className="rounded-full bg-white/20 px-4 py-2 text-sm font-semibold text-white">
                                                                                                                                                                                                                                            OPN Testnet
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                      {/* Buttons */}
                                                                                                                                                                                                                                                                              <div className="mt-8 grid grid-cols-3 gap-3">

                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                    onClick={onReceive}
                                                                                                                                                                                                                                                                                                                className="rounded-2xl bg-white/20 py-3 text-sm font-semibold text-white transition hover:bg-white/30"
                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                      📥
                                                                                                                                                                                                                                                                                                                                                  <br />
                                                                                                                                                                                                                                                                                                                                                              Receive
                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                              onClick={onScanner}
                                                                                                                                                                                                                                                                                                                                                                                                          className="rounded-2xl bg-white/20 py-3 text-sm font-semibold text-white transition hover:bg-white/30"
                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                📷
                                                                                                                                                                                                                                                                                                                                                                                                                                            <br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Scanner
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={onVirtualCard}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="rounded-2xl bg-white/20 py-3 text-sm font-semibold text-white transition hover:bg-white/30"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          💳
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Card
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }