"use client";

import { useEffect, useState } from "react";

type Tx = {
  id: string;
    type: "send" | "receive";
      amount: string;
        token: string;
          status: "pending" | "success";
            to: string;
              time: string;
              };

              export default function PayEngine() {
                const [transactions, setTransactions] = useState<Tx[]>([]);
                  const [gas, setGas] = useState("standard");
                    const [slippage, setSlippage] = useState(0.5);

                      const [loading, setLoading] = useState(false);
                        const [success, setSuccess] = useState(false);

                          const [cardActive, setCardActive] = useState(false);

                            /* ================= MOCK BLOCKCHAIN INDEXER ================= */
                              useEffect(() => {
                                  const mock: Tx[] = [
                                        {
                                                id: "1",
                                                        type: "send",
                                                                amount: "12.5",
                                                                        token: "OPN",
                                                                                status: "success",
                                                                                        to: "0x123...abc",
                                                                                                time: "2m ago",
                                                                                                      },
                                                                                                            {
                                                                                                                    id: "2",
                                                                                                                            type: "receive",
                                                                                                                                    amount: "5.0",
                                                                                                                                            token: "WOPN",
                                                                                                                                                    status: "success",
                                                                                                                                                            to: "0x456...def",
                                                                                                                                                                    time: "10m ago",
                                                                                                                                                                          },
                                                                                                                                                                              ];

                                                                                                                                                                                  setTransactions(mock);
                                                                                                                                                                                    }, []);

                                                                                                                                                                                      /* ================= FAKE TX ================= */
                                                                                                                                                                                        function simulateTx() {
                                                                                                                                                                                            setLoading(true);
                                                                                                                                                                                                setSuccess(false);

                                                                                                                                                                                                    setTimeout(() => {
                                                                                                                                                                                                          setLoading(false);
                                                                                                                                                                                                                setSuccess(true);

                                                                                                                                                                                                                      setTimeout(() => setSuccess(false), 2000);
                                                                                                                                                                                                                          }, 2000);
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                  <div className="mt-8 space-y-6">

                                                                                                                                                                                                                                        {/* ================= GAS + SLIPPAGE ================= */}
                                                                                                                                                                                                                                              <div className="rounded-3xl border border-white/10 bg-white/5 p-5">
                                                                                                                                                                                                                                                      <h3 className="text-lg font-bold">Transaction Settings</h3>

                                                                                                                                                                                                                                                              <div className="mt-4 grid grid-cols-2 gap-4">

                                                                                                                                                                                                                                                                        {/* GAS */}
                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                              <p className="text-xs text-white/50 mb-2">Gas Mode</p>
                                                                                                                                                                                                                                                                                                          <select
                                                                                                                                                                                                                                                                                                                        value={gas}
                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setGas(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                    className="w-full rounded-xl bg-black border border-white/10 p-3"
                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                              <option value="low">Low</option>
                                                                                                                                                                                                                                                                                                                                                                                            <option value="standard">Standard</option>
                                                                                                                                                                                                                                                                                                                                                                                                          <option value="fast">Fast</option>
                                                                                                                                                                                                                                                                                                                                                                                                                      </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* SLIPPAGE */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-xs text-white/50 mb-2">Slippage (%)</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={slippage}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setSlippage(Number(e.target.value))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full rounded-xl bg-black border border-white/10 p-3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* ================= VIRTUAL CARD ================= */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="rounded-3xl border border-white/10 bg-gradient-to-br from-purple-500/10 to-cyan-500/10 p-5">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="text-lg font-bold">Virtual Card</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-sm text-white/60 mt-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Web3 card system (testnet mode)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="mt-4 flex items-center justify-between">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Status:{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className={cardActive ? "text-green-400" : "text-red-400"}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {cardActive ? "ACTIVE" : "INACTIVE"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setCardActive(!cardActive)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="rounded-xl bg-white text-black px-4 py-2 font-bold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {cardActive ? "Freeze" : "Activate"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* ================= TX BUTTON ================= */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={simulateTx}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full rounded-2xl bg-gradient-to-r from-cyan-400 to-purple-500 p-4 font-bold text-black"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Simulate Transaction
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* ================= LOADING ================= */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {loading && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="rounded-2xl bg-yellow-500/10 border border-yellow-400/20 p-4 text-yellow-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Processing transaction...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* ================= SUCCESS ================= */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {success && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="rounded-2xl bg-green-500/10 border border-green-400/20 p-4 text-green-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Transaction confirmed ✔
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* ================= HISTORY ================= */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="rounded-3xl border border-white/10 bg-white/5 p-5">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="text-lg font-bold">Transaction History</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-4 space-y-3">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {transactions.map((tx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={tx.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="flex justify-between items-center rounded-xl bg-black/40 p-3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {tx.type.toUpperCase()} {tx.amount} {tx.token}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-xs text-white/50">{tx.to}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-xs text-green-400">{tx.time}</span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }