"use client";

import { useAccount } from "wagmi";
import { QRCodeSVG } from "qrcode.react";
import { useState } from "react";

export default function ReceiveTab() {
  const { address, isConnected } = useAccount();
    const [copied, setCopied] = useState(false);

      async function copyAddress() {
          if (!address) return;
              await navigator.clipboard.writeText(address);
                  setCopied(true);
                      setTimeout(() => setCopied(false), 1500);
                        }

                          const short =
                              address && address.length > 10
                                    ? `${address.slice(0, 6)}...${address.slice(-4)}`
                                          : "Not Connected";

                                            return (
                                                <div className="flex flex-col items-center justify-center text-center">

                                                      {/* TITLE */}
                                                            <h2 className="text-xl font-bold text-white">Receive Payment</h2>
                                                                  <p className="text-sm text-white/50 mt-1">
                                                                          Share your QR code to receive crypto
                                                                                </p>

                                                                                      {/* QR CENTER CARD */}
                                                                                            <div className="relative mt-6 rounded-3xl border border-white/10 bg-gradient-to-br from-black via-[#0b1020] to-[#0a0f1f] p-6 shadow-2xl">

                                                                                                    <div className="absolute -top-10 -right-10 h-40 w-40 rounded-full bg-cyan-500/20 blur-3xl" />
                                                                                                            <div className="absolute -bottom-10 -left-10 h-40 w-40 rounded-full bg-purple-500/20 blur-3xl" />

                                                                                                                    <div className="relative z-10 flex flex-col items-center">

                                                                                                                              {/* QR */}
                                                                                                                                        <div className="rounded-2xl bg-white p-3">
                                                                                                                                                    <QRCodeSVG value={address || ""} size={180} />
                                                                                                                                                              </div>

                                                                                                                                                                        {/* ADDRESS */}
                                                                                                                                                                                  <p className="mt-4 text-xs text-white/40">Wallet Address</p>
                                                                                                                                                                                            <p className="mt-1 text-sm font-semibold text-cyan-300 break-all max-w-[240px]">
                                                                                                                                                                                                        {short}
                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                            {/* FULL ADDRESS */}
                                                                                                                                                                                                                                      <p className="mt-2 text-[10px] text-white/30 break-all max-w-[280px]">
                                                                                                                                                                                                                                                  {address}
                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                      {/* ACTIONS */}
                                                                                                                                                                                                                                                                                <div className="mt-5 flex gap-3 w-full">

                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                          onClick={copyAddress}
                                                                                                                                                                                                                                                                                                                        className="flex-1 rounded-2xl bg-cyan-500/10 border border-cyan-400/20 px-4 py-3 text-sm font-semibold text-cyan-300 hover:bg-cyan-500/20 transition"
                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                  {copied ? "Copied ✓" : "Copy"}
                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => window.open(`https://explorer.io/${address}`, "_blank")}
                                                                                                                                                                                                                                                                                                                                                                                                      className="flex-1 rounded-2xl bg-white/5 border border-white/10 px-4 py-3 text-sm font-semibold hover:bg-white/10 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                Explorer
                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* INFO CARD */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-6 w-full rounded-2xl border border-white/10 bg-white/5 p-4 text-left">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-sm font-semibold text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ⚡ How to receive
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ul className="mt-2 space-y-1 text-xs text-white/60">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <li>• Share this QR with sender</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <li>• Supports OPN + ERC20 tokens</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li>• Works on IOPN Testnet</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </ul>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }