"use client";

import { useEffect, useState } from "react";

type Props = {
  onScan: (value: string) => void;
  };

  export default function ScannerTab({ onScan }: Props) {
    const [error, setError] = useState<string>("");

      useEffect(() => {
          let scanner: any;

              async function startScanner() {
                    try {
                            const { Html5QrcodeScanner } = await import("html5-qrcode");

                                    scanner = new Html5QrcodeScanner(
                                              "qr-reader",
                                                        {
                                                                    fps: 10,
                                                                                qrbox: { width: 260, height: 260 },
                                                                                            aspectRatio: 1,
                                                                                                      },
                                                                                                                false
                                                                                                                        );

                                                                                                                                scanner.render(
                                                                                                                                          (decodedText: string) => {
                                                                                                                                                      onScan(decodedText);

                                                                                                                                                                  // stop scanner after scan (important UX)
                                                                                                                                                                              scanner.clear();
                                                                                                                                                                                        },
                                                                                                                                                                                                  (err: any) => {
                                                                                                                                                                                                              // ignore scanning noise
                                                                                                                                                                                                                          console.log(err);
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                  } catch (e) {
                                                                                                                                                                                                                                                          setError("Camera not available or permission denied.");
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                        startScanner();

                                                                                                                                                                                                                                                                            return () => {
                                                                                                                                                                                                                                                                                  if (scanner) {
                                                                                                                                                                                                                                                                                          scanner.clear().catch(() => {});
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                      }, [onScan]);

                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                            <div className="flex flex-col items-center justify-center">

                                                                                                                                                                                                                                                                                                                  <h2 className="text-xl font-bold">Scan QR Code</h2>
                                                                                                                                                                                                                                                                                                                        <p className="text-sm text-white/50 mt-1">
                                                                                                                                                                                                                                                                                                                                Scan wallet address to auto-fill payment
                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                            {/* SCANNER BOX */}
                                                                                                                                                                                                                                                                                                                                                  <div className="mt-6 w-full max-w-sm rounded-3xl border border-white/10 bg-black/40 p-4 backdrop-blur-xl">

                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                    id="qr-reader"
                                                                                                                                                                                                                                                                                                                                                                              className="overflow-hidden rounded-2xl"
                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                  {/* HELP TEXT */}
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-5 text-center text-xs text-white/50">
                                                                                                                                                                                                                                                                                                                                                                                                                Point your camera at a wallet QR code or payment link
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                            {/* ERROR */}
                                                                                                                                                                                                                                                                                                                                                                                                                                  {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-4 rounded-xl bg-red-500/10 border border-red-500/20 px-4 py-2 text-sm text-red-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }