"use client";

import { useMemo, useState } from "react";
import { useAccount, useBalance, useSendTransaction, useWriteContract } from "wagmi";
import { parseUnits } from "viem";
import { TOKENS } from "../lib/constants";
import { ERC20_ABI } from "../lib/payments";

export default function SendTab() {
  const { address, isConnected } = useAccount();

    const [tokenSymbol, setTokenSymbol] = useState("OPN");
      const [to, setTo] = useState("");
        const [amount, setAmount] = useState("");

          const token = useMemo(
              () => TOKENS.find((t) => t.symbol === tokenSymbol)!,
                  [tokenSymbol]
                    );

                      const { data: balance } = useBalance({ address });

                        const parsedAmount = amount
                            ? parseUnits(amount, token.decimals)
                                : undefined;

                                  const canSend =
                                      isConnected &&
                                          to.startsWith("0x") &&
                                              to.length === 42 &&
                                                  amount &&
                                                      Number(amount) > 0 &&
                                                          parsedAmount;

                                                            const { sendTransaction, isPending: nativeLoading } = useSendTransaction();
                                                              const { writeContract, isPending: erc20Loading } = useWriteContract();

                                                                const loading = nativeLoading || erc20Loading;

                                                                  function handleMax() {
                                                                      if (!balance?.formatted) return;
                                                                          setAmount(Number(balance.formatted).toFixed(4));
                                                                            }

                                                                              async function handleSend() {
                                                                                  if (!canSend || !parsedAmount) return;

                                                                                      try {
                                                                                            if (token.native) {
                                                                                                    // NATIVE OPN TRANSFER
                                                                                                            sendTransaction({
                                                                                                                      to: to as `0x${string}`,
                                                                                                                                value: parsedAmount,
                                                                                                                                        });
                                                                                                                                              } else {
                                                                                                                                                      // ERC20 TRANSFER
                                                                                                                                                              writeContract({
                                                                                                                                                                        address: token.address as `0x${string}`,
                                                                                                                                                                                  abi: ERC20_ABI,
                                                                                                                                                                                            functionName: "transfer",
                                                                                                                                                                                                      args: [to as `0x${string}`, parsedAmount],
                                                                                                                                                                                                              });
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                    await fetch("http://localhost:4000/api/save-tx", {
                                                                                                                                                                                                                          method: "POST",
                                                                                                                                                                                                                            headers: { "Content-Type": "application/json" },
                                                                                                                                                                                                                              body: JSON.stringify({
                                                                                                                                                                                                                                  hash: txHash,
                                                                                                                                                                                                                                      from: address,
                                                                                                                                                                                                                                          to,
                                                                                                                                                                                                                                              amount,
                                                                                                                                                                                                                                                  token: token.symbol,
                                                                                                                                                                                                                                                      status: "confirmed",
                                                                                                                                                                                                                                                          chainId: 984,
                                                                                                                                                                                                                                                            }),
                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                              console.log("Send error:", err);
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                          <div className="rounded-3xl border border-white/10 bg-white/5 p-5 backdrop-blur-xl">

                                                                                                                                                                                                                                                <h2 className="text-xl font-bold text-white">Send Payment</h2>
                                                                                                                                                                                                                                                      <p className="text-sm text-white/50">
                                                                                                                                                                                                                                                              Transfer crypto on IOPN Testnet
                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                          {/* TOKEN SELECT */}
                                                                                                                                                                                                                                                                                <select
                                                                                                                                                                                                                                                                                        value={tokenSymbol}
                                                                                                                                                                                                                                                                                                onChange={(e) => setTokenSymbol(e.target.value)}
                                                                                                                                                                                                                                                                                                        className="mt-4 w-full rounded-2xl bg-black/30 border border-white/10 p-3"
                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                      {TOKENS.map((t) => (
                                                                                                                                                                                                                                                                                                                                <option key={t.symbol} value={t.symbol}>
                                                                                                                                                                                                                                                                                                                                            {t.symbol}
                                                                                                                                                                                                                                                                                                                                                      </option>
                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                    </select>

                                                                                                                                                                                                                                                                                                                                                                          {/* BALANCE */}
                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-3 text-sm text-cyan-300">
                                                                                                                                                                                                                                                                                                                                                                                        Balance: {balance?.formatted ? Number(balance.formatted).toFixed(4) : "0.00"} {token.symbol}
                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                    {/* TO */}
                                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                                  value={to}
                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setTo(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Recipient address (0x...)"
                                                                                                                                                                                                                                                                                                                                                                                                                                          className="mt-4 w-full rounded-2xl bg-black/30 border border-white/10 p-3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* AMOUNT */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="relative mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={amount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setAmount(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Amount"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-full rounded-2xl bg-black/30 border border-white/10 p-3 text-lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={handleMax}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="absolute right-3 top-2 rounded-xl bg-cyan-500/20 px-3 py-1 text-xs text-cyan-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  MAX
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* SEND BUTTON */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={handleSend}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            disabled={!canSend || loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={`mt-5 w-full rounded-2xl p-4 font-bold transition ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              canSend
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ? "bg-gradient-to-r from-cyan-400 to-purple-500 text-black hover:scale-[1.02]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      : "bg-white/10 text-white/40"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {loading ? "Sending..." : "Send Payment"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }