"use client";

import { useState } from "react";

type Props = {
  recipient: string;
    setRecipient: (value: string) => void;

      amount: string;
        setAmount: (value: string) => void;

          tokenSymbol: string;

            balance: string;

              onSend: () => Promise<void>;
              };

              export default function SendForm({
                recipient,
                  setRecipient,
                    amount,
                      setAmount,
                        tokenSymbol,
                          balance,
                            onSend,
                            }: Props) {
                              const [loading, setLoading] = useState(false);

                                async function handleSend() {
                                    try {
                                          setLoading(true);
                                                await onSend();
                                                    } finally {
                                                          setLoading(false);
                                                              }
                                                                }

                                                                  return (
                                                                      <div className="mt-6 rounded-3xl border border-white/10 bg-white/5 p-5">

                                                                            {/* TITLE */}

                                                                                  <div className="mb-5 flex items-center justify-between">

                                                                                          <div>
                                                                                                    <h2 className="text-lg font-bold text-white">
                                                                                                                Send Payment
                                                                                                                          </h2>

                                                                                                                                    <p className="text-sm text-white/50">
                                                                                                                                                Fast blockchain payment
                                                                                                                                                          </p>
                                                                                                                                                                  </div>

                                                                                                                                                                          <div className="rounded-full bg-green-500/20 px-3 py-1 text-xs text-green-400">
                                                                                                                                                                                    {tokenSymbol}
                                                                                                                                                                                            </div>

                                                                                                                                                                                                  </div>

                                                                                                                                                                                                        {/* RECIPIENT */}

                                                                                                                                                                                                              <div className="mb-4">

                                                                                                                                                                                                                      <label className="mb-2 block text-sm text-white/70">
                                                                                                                                                                                                                                Recipient
                                                                                                                                                                                                                                        </label>

                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                          value={recipient}
                                                                                                                                                                                                                                                                    onChange={(e) => setRecipient(e.target.value)}
                                                                                                                                                                                                                                                                              placeholder="0x..."
                                                                                                                                                                                                                                                                                        className="w-full rounded-2xl border border-white/10 bg-black/20 p-4 text-white outline-none"
                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                            {/* AMOUNT */}

                                                                                                                                                                                                                                                                                                                  <div>

                                                                                                                                                                                                                                                                                                                          <div className="mb-2 flex justify-between">

                                                                                                                                                                                                                                                                                                                                    <label className="text-sm text-white/70">
                                                                                                                                                                                                                                                                                                                                                Amount
                                                                                                                                                                                                                                                                                                                                                          </label>

                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                type="button"
                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => setAmount(balance)}
                                                                                                                                                                                                                                                                                                                                                                                                        className="text-sm text-green-400"
                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                              MAX
                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex overflow-hidden rounded-2xl border border-white/10 bg-black/20">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={amount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setAmount(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="0.00"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="flex-1 bg-transparent p-4 text-white outline-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex items-center px-4 text-white/60">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {tokenSymbol}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* BALANCE */}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-3 text-right text-xs text-white/50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Available: {balance} {tokenSymbol}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* SEND */}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={handleSend}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="mt-6 w-full rounded-2xl bg-green-500 py-4 text-lg font-bold text-black transition hover:bg-green-400 disabled:opacity-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {loading ? "Sending..." : "Send Payment"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }