"use client";

import { useEffect, useState } from "react";

const API = "https://iopndex.onrender.com";

type Tx = {
  from: string;
    to: string;
      amount: string;
        token: string;
          hash: string;
            status?: "pending" | "confirmed" | "failed";
              createdAt?: string;
              };

              type Props = {
                address?: string;
                  liveTxs: Tx[];
                  };

                  export default function TransactionHistory({
                    address,
                      liveTxs,
                      }: Props) {
                        const [history, setHistory] = useState<Tx[]>([]);

                          /* ================= LOAD HISTORY ================= */
                            useEffect(() => {
                                async function load() {
                                      try {
                                              if (!address) return;

                                                      const res = await fetch(
                                                                `${API}/api/history?address=${address}`
                                                                        );

                                                                                const data = await res.json();

                                                                                        if (data?.history) {
                                                                                                  setHistory(data.history);
                                                                                                          }
                                                                                                                } catch (err) {
                                                                                                                        console.error("History load failed:", err);
                                                                                                                              }
                                                                                                                                  }

                                                                                                                                      load();
                                                                                                                                        }, [address]);

                                                                                                                                          /* ================= MERGE LIVE + HISTORY ================= */
                                                                                                                                            const merged = [...liveTxs, ...history];

                                                                                                                                              return (
                                                                                                                                                  <div className="mt-10">

                                                                                                                                                        {/* TITLE */}
                                                                                                                                                              <h2 className="mb-4 text-lg font-bold text-white">
                                                                                                                                                                      Transaction History
                                                                                                                                                                            </h2>

                                                                                                                                                                                  {/* EMPTY STATE */}
                                                                                                                                                                                        {merged.length === 0 && (
                                                                                                                                                                                                <p className="text-white/40">
                                                                                                                                                                                                          No transactions yet
                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                              {/* LIST */}
                                                                                                                                                                                                                                    <div className="space-y-3">

                                                                                                                                                                                                                                            {merged.map((tx, i) => (
                                                                                                                                                                                                                                                      <div
                                                                                                                                                                                                                                                                  key={i}
                                                                                                                                                                                                                                                                              className="rounded-2xl border border-white/10 bg-white/5 p-4"
                                                                                                                                                                                                                                                                                        >

                                                                                                                                                                                                                                                                                                    {/* FROM → TO */}
                                                                                                                                                                                                                                                                                                                <p className="text-sm text-white/60 break-all">
                                                                                                                                                                                                                                                                                                                              {tx.from} → {tx.to}
                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                      {/* AMOUNT */}
                                                                                                                                                                                                                                                                                                                                                                  <p className="mt-1 text-green-400 font-bold">
                                                                                                                                                                                                                                                                                                                                                                                {tx.amount} {tx.token}
                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                        {/* STATUS */}
                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="mt-2 flex items-center justify-between">

                                                                                                                                                                                                                                                                                                                                                                                                                                  <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                  className={`text-xs ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tx.status === "confirmed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ? "text-green-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : tx.status === "failed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ? "text-red-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : "text-yellow-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {tx.status || "pending"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* HASH LINK */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href={`https://testnet.iopn.tech/tx/${tx.hash}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="text-xs text-blue-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          View
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }