"use client";

import { useAccount, useBalance } from "wagmi";
import WalletButton from "@/components/WalletButton";

export default function Home() {
  const { address, isConnected } = useAccount();
  const { data: opnBalance } = useBalance({
    address,
    });

    return (
        <main className="min-h-screen text-white pb-24 bg-gradient-to-b from-purple-950 via-black to-green-950">

              <div className="p-5">

                      {/* Header */}
                              <div className="rounded-3xl p-6 bg-white/5 backdrop-blur-lg border border-purple-500/30">
                                <div className="flex items-center justify-between">

                                    <div>
                                          <h1 className="text-4xl font-extrabold bg-gradient-to-r from-purple-400 to-green-400 bg-clip-text text-transparent">
                                                  IOPn Dex
                                                        </h1>

                                                              <p className="text-zinc-400 mt-2">
                                                                      Trade • Pay • Earn on OPN Testnet
                                                                            </p>
                                                                                </div>

                                                                                    <WalletButton />

                                                                                      </div>
                                                                                      </div>

                                                                                                              {/* Wallet Card */}
                                                                                                                      <div className="mt-6 rounded-3xl p-6 bg-gradient-to-r from-purple-600 to-green-500">

                                                                                                                                <p className="text-sm opacity-80">
                                                                                                                                            Wallet Status
                                                                                                                                                      </p>

                                                                                                                                                                <h2 className="text-xl font-bold mt-2 break-all">
                                                                                                                                                                            {isConnected
                                                                                                                                                                                          ? `${address?.slice(0, 6)}...${address?.slice(-4)}`
                                                                                                                                                                                                        : "Wallet Not Connected"}
                                                                                                                                                                                                                  </h2>

                                                                                                                                                                                                                            <div className="mt-3">
                                                                                                                                                                                                                                  <p className="text-sm">
                                                                                                                                                                                                                                      OPN Testnet • Chain ID 984
                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                          <p className="font-bold text-lg mt-2">
                                                                                                                                                                                                                                              {opnBalance?.formatted
                                                                                                                                                                                                                                                    ? Number(opnBalance.formatted).toFixed(4)
                                                                                                                                                                                                                                                          : "0.0000"} OPN
                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                  {/* Quick Actions */}
                                                                                                                                                                                                                                                                          <div className="grid grid-cols-2 gap-4 mt-6">

                                                                                                                                                                                                                                                                                    <a
                                                                                                                                                                                                                                                                                                href="/pay"
                                                                                                                                                                                                                                                                                                            className="rounded-3xl p-6 bg-green-500 text-black font-bold text-center"
                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                  💸 PAY
                                                                                                                                                                                                                                                                                                                                            </a>

                                                                                                                                                                                                                                                                                                                                                      <a
                                                                                                                                                                                                                                                                                                                                                                  href="/trade"
                                                                                                                                                                                                                                                                                                                                                                              className="rounded-3xl p-6 bg-purple-500 font-bold text-center"
                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                    🔄 TRADE
                                                                                                                                                                                                                                                                                                                                                                                                              </a>

                                                                                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                                                                                    href="/staking"
                                                                                                                                                                                                                                                                                                                                                                                                                                                className="rounded-3xl p-6 bg-yellow-500 text-black font-bold text-center"
                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      💎 STAKE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      href="/portfolio"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="rounded-3xl p-6 bg-blue-500 font-bold text-center"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        💼 WALLET
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Supported Tokens */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-6 rounded-3xl p-6 bg-white/5 backdrop-blur-lg border border-white/10">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="text-xl font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Supported Tokens
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="space-y-3 mt-4">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span>WOPN</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>OPN Testnet</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span>OPNT</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>OPN Testnet</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span>tUSDT</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>OPN Testnet</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span>tBNB</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>OPN Testnet</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Announcement Board */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-6 rounded-3xl p-6 bg-white/5 backdrop-blur-lg border border-white/10">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-xl font-semibold mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            📢 Ecosystem Updates
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <ul className="space-y-2 text-zinc-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <li>🚀 OPN Testnet Live</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li>💸 IOPn Pay Available</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <li>🔄 Trade OPNT & WOPN</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li>💎 Staking Coming Soon</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <li>🎁 Ecosystem Rewards Coming</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </ul>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* QUICK LINKS */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="mt-6 rounded-3xl border border-white/10 bg-[#111111] p-6">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-lg font-bold text-white mb-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    🌐 Quick Links
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="grid grid-cols-3 gap-4">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="https://x.com/iopndex_xyz"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="rounded-2xl border border-white/10 bg-black/40 p-4 text-center hover:border-cyan-400 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-3xl mb-2">𝕏</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-sm text-white/80">X</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="https://faucet.iopn.tech"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="rounded-2xl border border-white/10 bg-black/40 p-4 text-center hover:border-cyan-400 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-3xl mb-2">🚰</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-sm text-white/80">Faucet</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="https://testnet.iopn.tech"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="rounded-2xl border border-white/10 bg-black/40 p-4 text-center hover:border-cyan-400 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-3xl mb-2">🔍</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-sm text-white/80">Explorer</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }