"use client";

import { formatUnits } from "viem";
import { usePortfolio } from "@/lib/usePortfolio";
import { TOKENS } from "@/lib/tokens";

export default function PortfolioPage() {
  const {
      address,
          nativeBalance,
              tokenBalances,
                } = usePortfolio();

                  const isConnected = !!address;

                    return (
                        <main className="min-h-screen pb-24 text-white bg-gradient-to-b from-slate-950 via-blue-950 to-black">
                              <div className="max-w-3xl mx-auto p-5">

                                      {/* Header */}
                                              <div className="rounded-3xl p-6 bg-gradient-to-r from-blue-600 via-purple-600 to-indigo-700 shadow-2xl">
                                                        <h1 className="text-4xl font-bold">
                                                                    💼 Portfolio
                                                                              </h1>

                                                                                        <p className="mt-2 text-white/80">
                                                                                                    Track your OPN Testnet assets
                                                                                                              </p>
                                                                                                                      </div>

                                                                                                                              {/* Wallet */}
                                                                                                                                      <div className="mt-5 flex items-center justify-between rounded-2xl border border-white/10 bg-white/5 backdrop-blur-xl p-4">
                                                                                                                                                <div>
                                                                                                                                                            <p className="text-xs text-zinc-400">
                                                                                                                                                                          Connected Wallet
                                                                                                                                                                                      </p>

                                                                                                                                                                                                  <p className="text-sm font-medium text-green-400">
                                                                                                                                                                                                                {isConnected
                                                                                                                                                                                                                                ? `${address?.slice(0, 6)}...${address?.slice(-4)}`
                                                                                                                                                                                                                                                : "Wallet Not Connected"}
                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                            <div className="h-2 w-2 rounded-full bg-green-500 animate-pulse" />
                                                                                                                                                                                                                                                                                                        <span className="text-xs text-zinc-400">
                                                                                                                                                                                                                                                                                                                      Online
                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                            {/* Native Balance Card */}
                                                                                                                                                                                                                                                                                                                                                                    <div className="mt-5 rounded-3xl bg-gradient-to-r from-cyan-600 via-blue-600 to-purple-700 p-6 shadow-2xl">
                                                                                                                                                                                                                                                                                                                                                                              <p className="text-sm text-white/80">
                                                                                                                                                                                                                                                                                                                                                                                          Total OPN Balance
                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="mt-2 text-5xl font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                          {nativeBalance.data
                                                                                                                                                                                                                                                                                                                                                                                                                                        ? Number(nativeBalance.data.formatted).toFixed(4)
                                                                                                                                                                                                                                                                                                                                                                                                                                                      : "0.0000"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="mt-2 text-white/80">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      OPN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Assets */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-6 rounded-3xl border border-white/10 bg-white/5 backdrop-blur-xl p-6">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2 className="text-xl font-semibold mb-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Assets
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="space-y-3">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Native OPN */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center justify-between rounded-2xl border border-cyan-500/20 bg-cyan-500/10 p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="font-semibold">OPN</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs text-zinc-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Native Token
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {nativeBalance.data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ? Number(nativeBalance.data.formatted).toFixed(4)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          : "0.0000"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* ERC20 Tokens */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {TOKENS.map((token, index) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const balance =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          tokenBalances?.data?.[index]?.result as bigint | undefined;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const formatted = balance
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ? Number(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            formatUnits(balance, token.decimals)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ).toFixed(4)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : "0.0000";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              key={token.symbol}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/5 p-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {token.symbol}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-xs text-zinc-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ERC20 Token
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {formatted}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }