"use client";

import { useAccount } from "wagmi";
import { QRCodeSVG } from "qrcode.react";
import { useState } from "react";

export default function PayPage() {
  const { address, isConnected } = useAccount();

    const [token, setToken] = useState("OPNT");
      const [recipient, setRecipient] = useState("");
        const [amount, setAmount] = useState("");

          return (
              <main className="min-h-screen pb-24 text-white bg-gradient-to-b from-green-950 via-black to-purple-950">
                    <div className="p-5">

                            <h1 className="text-4xl font-bold mb-6">
                                      💸 IOPn Pay
                                              </h1>

                                                      {/* Wallet Status */}
                                                              <div className="rounded-3xl p-5 bg-white/5 backdrop-blur-lg border border-white/10 mb-6">
                                                                        <h2 className="font-semibold text-lg mb-2">
                                                                                    Connected Wallet
                                                                                              </h2>

                                                                                                        {isConnected ? (
                                                                                                                    <p className="break-all text-green-400">
                                                                                                                                  {address}
                                                                                                                                              </p>
                                                                                                                                                        ) : (
                                                                                                                                                                    <p className="text-red-400">
                                                                                                                                                                                  Wallet Not Connected
                                                                                                                                                                                              </p>
                                                                                                                                                                                                        )}
                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                        {/* Send Section */}
                                                                                                                                                                                                                                <div className="rounded-3xl p-6 bg-white/5 backdrop-blur-lg border border-white/10">

                                                                                                                                                                                                                                          <h2 className="text-xl font-semibold mb-4">
                                                                                                                                                                                                                                                      Send Payment
                                                                                                                                                                                                                                                                </h2>

                                                                                                                                                                                                                                                                          <select
                                                                                                                                                                                                                                                                                      value={token}
                                                                                                                                                                                                                                                                                                  onChange={(e) => setToken(e.target.value)}
                                                                                                                                                                                                                                                                                                              className="w-full p-4 rounded-2xl bg-black/40 mb-4"
                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                    <option>OPNT</option>
                                                                                                                                                                                                                                                                                                                                                <option>tUSDT</option>
                                                                                                                                                                                                                                                                                                                                                            <option>tBNB</option>
                                                                                                                                                                                                                                                                                                                                                                        <option>WOPN</option>
                                                                                                                                                                                                                                                                                                                                                                                  </select>

                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                        value={recipient}
                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setRecipient(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Recipient Address"
                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-full p-4 rounded-2xl bg-black/40 mb-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={amount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setAmount(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="Amount"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-full p-4 rounded-2xl bg-black/40 mb-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button className="w-full p-4 rounded-2xl bg-green-500 text-black font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Send {token}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button className="w-full p-4 rounded-2xl bg-purple-500 font-bold mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            📷 Scan QR (Coming Soon)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Receive Section */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="mt-6 rounded-3xl p-6 bg-white/5 backdrop-blur-lg border border-white/10">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2 className="text-xl font-semibold mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Receive Payment
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {isConnected && address ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex justify-center mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <QRCodeSVG
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={address}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      size={180}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="break-all text-center text-sm text-zinc-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {address}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                navigator.clipboard.writeText(address)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="mt-4 w-full p-3 rounded-xl bg-blue-500 font-bold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Copy Address
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-zinc-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Connect wallet to generate your payment QR code.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Announcement Board */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-6 rounded-3xl p-6 bg-white/5 backdrop-blur-lg border border-white/10">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className="text-xl font-semibold mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                📢 Announcements
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ul className="space-y-2 text-zinc-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li>🚀 OPN Testnet Live</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <li>💸 Instant Payments Available</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li>🔄 Trade OPNT & WOPN</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <li>💎 Staking Launching Soon</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li>🎁 Ecosystem Rewards Coming</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }