"use client";

import { useEffect, useMemo, useState } from "react";
import { useAccount, useBalance, useSendTransaction } from "wagmi";
import { parseEther } from "viem";
import { io } from "socket.io-client";
import { TOKENS } from "@/lib/tokens";
import { sendTx as backendSendTx } from "@/lib/api";

/* ================= SOCKET (PRODUCTION FIX) ================= */
const socket = io("https://iopndex.onrender.com");

/* ================= UTIL ================= */
function formatBalance(value: any) {
  if (!value) return "0.00";
    return Number(value.formatted || 0).toFixed(2);
    }

    /* ================= PAGE ================= */
    export default function PayPage() {
      const { address, isConnected } = useAccount();

        const [recipient, setRecipient] = useState("");
          const [amount, setAmount] = useState("");
            const [tokenSymbol, setTokenSymbol] = useState("OPN");
              const [txHash, setTxHash] = useState<string | null>(null);
                const [liveTxs, setLiveTxs] = useState<any[]>([]);

                  const token = useMemo(
                      () => TOKENS.find((t) => t.symbol === tokenSymbol),
                          [tokenSymbol]
                            );

                              const { data: balance } = useBalance({ address });
                                const { sendTransactionAsync } = useSendTransaction();

                                  /* ================= SEND TX ================= */
                                    async function sendTx() {
                                        try {
                                              if (!isConnected || !address) {
                                                      alert("Connect wallet first");
                                                              return;
                                                                    }

                                                                          if (!recipient || !amount) {
                                                                                  alert("Missing fields");
                                                                                          return;
                                                                                                }

                                                                                                      // 1. blockchain tx
                                                                                                            const hash = await sendTransactionAsync({
                                                                                                                    to: recipient as `0x${string}`,
                                                                                                                            value: parseEther(amount),
                                                                                                                                  });

                                                                                                                                        setTxHash(hash);

                                                                                                                                              // 2. backend sync (FIXED PARAMS)
                                                                                                                                                    const res = await backendSendTx(
                                                                                                                                                            address,
                                                                                                                                                                    recipient,
                                                                                                                                                                            amount,
                                                                                                                                                                                    tokenSymbol,
                                                                                                                                                                                            hash,
                                                                                                                                                                                                    984
                                                                                                                                                                                                          );

                                                                                                                                                                                                                if (!res.success) {
                                                                                                                                                                                                                        alert("Backend failed ❌");
                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                      setRecipient("");
                                                                                                                                                                                                                                              setAmount("");
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                              console.error(err);
                                                                                                                                                                                                                                                                    alert("Transaction failed ❌");
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                            /* ================= SOCKET ================= */
                                                                                                                                                                                                                                                                              useEffect(() => {
                                                                                                                                                                                                                                                                                  socket.on("newTx", (tx) => {
                                                                                                                                                                                                                                                                                        setLiveTxs((prev) => [tx, ...prev]);
                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                socket.on("txConfirmed", (data) => {
                                                                                                                                                                                                                                                                                                      setLiveTxs((prev) =>
                                                                                                                                                                                                                                                                                                              prev.map((tx) =>
                                                                                                                                                                                                                                                                                                                        tx.hash === data.hash ? { ...tx, status: "confirmed" } : tx
                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                              return () => {
                                                                                                                                                                                                                                                                                                                                                    socket.disconnect();
                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                          }, []);

                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                <div className="min-h-screen bg-gradient-to-b from-black via-[#04130a] to-black text-white p-4">

                                                                                                                                                                                                                                                                                                                                                                      {/* HEADER (WEB3 STYLE) */}
                                                                                                                                                                                                                                                                                                                                                                            <div className="rounded-3xl p-5 bg-gradient-to-r from-green-600/30 to-emerald-500/20 border border-green-500/30">
                                                                                                                                                                                                                                                                                                                                                                                    <h1 className="text-3xl font-bold">IOPn Pay</h1>
                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-white/70 text-sm mt-1">
                                                                                                                                                                                                                                                                                                                                                                                                      Send assets securely on IOPn Testnet
                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-4 p-3 bg-black/40 rounded-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                Balance: <b>{formatBalance(balance)} {tokenSymbol}</b>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                {txHash && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-xs text-green-400 mt-2 break-all">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Tx: {txHash}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* TOKEN SELECTOR */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={tokenSymbol}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setTokenSymbol(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full p-3 bg-white/10 rounded-xl"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {TOKENS.map((t) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option key={t.symbol} value={t.symbol}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {t.symbol}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* INPUTS */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="space-y-3 mt-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full p-3 bg-white/10 rounded-xl"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="Recipient address"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value={recipient}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setRecipient(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="w-full p-3 bg-white/10 rounded-xl"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Amount"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={amount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setAmount(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* ACTION BUTTONS (RESTORED FEATURES) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="grid grid-cols-3 gap-2 mt-4">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button className="bg-green-500 text-black font-bold p-2 rounded-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SEND
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button className="bg-blue-500 text-white font-bold p-2 rounded-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          RECEIVE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button className="bg-purple-500 text-white font-bold p-2 rounded-xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CARD
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={sendTx}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full mt-4 p-3 bg-green-600 text-black font-bold rounded-xl"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Send Transaction
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* LIVE TX */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="font-bold text-lg mb-2">Live Transactions</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {liveTxs.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-white/40">No transactions yet</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {liveTxs.map((tx, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div key={i} className="p-3 border-b border-white/10">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-sm">{tx.from} → {tx.to}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-green-400">{tx.amount} {tx.token}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-xs text-white/40">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {tx.status || "pending"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }